### ISSUE TITLE
Can't start plugin

### ISSUE THREAD

**Issue by abalmos** [barreiroleo/ltex_extra.nvim#10]
**Describe the bug**
Plugin errors due to serialization issue

**To Reproduce**
1. Install plugin
2. Use default config
3. Start nvim on a `tex` file.

**Expected behavior**
The plugin to start

**Screenshots**
![image](https://user-images.githubusercontent.com/1865093/185807009-241ce610-e955-4dc7-8600-7b61e07336fd.png)

**Desktop (please complete the following information):**
nvim 0.8 master build

**Additional context**
With a quick look through the code, I don't see where the issue is.

**Comment by abalmos** [comment]
Sorry for the noise. I had an odd typo in a far away lua config file that made things fail in strange ways. `ltex_extra` is working fine for me now. Thanks for creating it!

**Comment by barreiroleo** [comment]
Hi @abalmos
Don't worry, things that happen. I'm glad to hear that, thank you for using it.
