### ISSUE TITLE
Problems with spanish

### ISSUE THREAD

**Issue by dgox16** [barreiroleo/ltex_extra.nvim#11]
I have exactly the same configuration (I also speak Spanish). But I can't get ltex with your plugin to use the spanish language. It works but it always detects English. Do you know what could be the reason?

**Comment by barreiroleo** [comment]
Hi @dgox16
Yeah, I have the same issue. Depends on the file type you can do something things:
On LaTeX files, you need use the package `babel` with `spanish`.
Also, for LaTeX included files and markdown files I use the LTeX [`magic comments`](https://valentjn.github.io/ltex/advanced-usage.html#magic-comments). You can see the [docs file](https://github.com/barreiroleo/ltex_extra.nvim/tree/master/docs) for examples.

On LaTeX, the magic comment shouldn't be necessary, but I believe there is something wrong with the `lsp-config` settings with the typical single-file mode. I don't have the opportunity yet to see under the hood.

**Comment by dgox16** [comment]
It's weird but even with the babel package it doesn't work in Spanish. The only way to make it work is with the grammar-guard plugin. But I like your implementation with the code actions.
