### ISSUE TITLE
grammar-guard.nvim

### ISSUE THREAD

**Issue by ayoubelmhamdi** [barreiroleo/ltex_extra.nvim#14]
It's looks like [grammar-guard.nvim](https://github.com/brymer-meneses/grammar-guard.nvim),
is there any difference between these two `plugins`

**Comment by barreiroleo** [comment]
Yeah, they are two different things.

Grammar-guard was a tool only for installing the LTeX server. Today, the server is available from `nvim-lsp-installer` or `Mason`, so the plugin is no more needed.

LTeX_extra, provide the missing functionalities that are out of spec of LSP (check the features).

**Comment by ayoubelmhamdi** [comment]
@barreiroleo , thank you, so much,

brief question : how can get the table of supported languages like 'fr'
```lua
    require('ltex_extra').setup {
      load_langs = { 'francais', 'en-US' }, -- table <string> : languages for witch dictionaries will be loaded
    }
```

**Comment by barreiroleo** [comment]
It's in the official docs of the server: [LTeX - Supported Languages](https://valentjn.github.io/ltex/supported-languages.html)

**Comment by ayoubelmhamdi** [comment]
thank you @barreiroleo

**Comment by barreiroleo** [comment]
You're welcome @ayoubelmhamdi, I hope the plugin helps you.
