### ISSUE TITLE
Disable missing-files warning when not using those files.

### ISSUE THREAD

**Issue by CharlesChiuGit** [barreiroleo/ltex_extra.nvim#16]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying to saw the missing-files warning when you actucally don't need that file.
For example, I only needs `ltex.dictionary.en-US.txt` in certain repo. The warnings of missing `ltex.disabledRules.en-US.txt` and `ltex.hiddenFalsePositives.en-US.txt` are a bit annoying. Even when I do need those files, `ltex_extra.nvim`'s code action will create it. So it's a bit confuse to see this kind of warning.

**Describe the solution you'd like**
Don't show miss-files warning even if there's only one of the three files is created.

**Describe alternatives you've considered**
I saw you add a related TODO of `Abort initial load if the files doesn't exist`, maybe you're already consider it? If so I will close the issue.

Thanks for creeating this handy plugin!

**Comment by barreiroleo** [comment]
Hello @CharlesChiuGit, I hope you're well.

What is the exact message? These files' warning and error logs are related to incorrect write permission.
Your scenario is habitual for me, and I can't reproduce your error.

The ToDo note is something about the architecture that I would to like change.

**Comment by CharlesChiuGit** [comment]
The warning:
![image](https://user-images.githubusercontent.com/32497323/200180238-68560570-515b-490e-b3a3-eb229234408e.png)

Files in `spell/`:
![image](https://user-images.githubusercontent.com/32497323/200180254-ff1fd262-8917-47bd-b946-98525cb79871.png)

**Comment by CharlesChiuGit** [comment]
The warning will be gone once I touch a empty file of `ltex.disabledRules.en-US.txt`, btw.

**Comment by barreiroleo** [comment]
I said nothing, it's just checking with the intention to say: "Hey, maybe you're on the wrong directory or something passed with your ltex files".

For now, you can simply pass a higher level for logs in the settings ([configuration](https://github.com/barreiroleo/ltex_extra.nvim#configuration)).
```lua
require("ltex_extra").setup{
    -- your settings
    log_level = "error", -- string : "none", "trace", "debug", "info", "warn", "error", "fatal"
}
```
Other workflows can be considered in the future, such as creating a config file on the spell path... I don't know

**Comment by CharlesChiuGit** [comment]
sure, thanks for the reply!

**Comment by barreiroleo** [comment]
It's a pleasure, I hope the plugin will be useful to you.
