### ISSUE TITLE
Home directory can't be accessed via ~ in ltex_extra path

### ISSUE THREAD

**Issue by HawkinsT** [barreiroleo/ltex_extra.nvim#19]
**Describe the bug**
Say I wish ltex_extra to save files to my home directory:
```lua
require("lspconfig").ltex.setup {
    on_attach = function(client, bufnr)
        require("ltex_extra").setup {
            load_langs = { "en-GB" },
            init_check = true,
            path = "~",
            log_level = "none",
        }
    end,
    settings = {
        ltex = {
            language = "en-GB",
        }
    }
}
```
This appears to be okay until ltex_extra tries to write to the specified path containing `~`, then it fails. For instance if I try to add a word to the ltex dictionary via a code action then it reports the following error:
```
Fail making directory
Fail export ~/ltex.dictionary.en-GB.txt
```
Presumably it thinks `~` is supposed to be the name of a regular directory and finds it can't name a directory this in the current path.

**Expected behavior**
In the above mentioned case, `ltex.dictionary.en-GB.txt` should be written to the home directory, `/home/username/ltex.dictionary.en-GB.txt`.

**System:**
 - OS: Linux
 - Neovim version: 0.9 Nightly
 - LTeX server intallation method: Mason

**Comment by ned-si** [comment]
Same behavior with `$HOME`. The workaround is to have `/home/username` instead.

**Comment by fhfuih** [comment]
A more canonical solution can be wrapping the path in `vim.fn.expand` or `vim.fs.normalize`.
The former one is the port from pure vim script function, and the latter one is a lua one with extra functionalities (details are on their `:h` pages.

I remember there are many other places where `~` is not expanded by default in (n)vim. So keep this trick in mind and hopefully it is helpful elsewhere.

BTW, it is possible that this func is added in the plugin's codes?

**Comment by fhfuih** [comment]
⬆️ Added a small PR to fix this bug (or — implement this feature?)
