### ISSUE TITLE
Files are written for ignored rules/ false positives  and dictionary, but they aren't ignored during linting

### ISSUE THREAD

**Issue by felipejoribeiro** [barreiroleo/ltex_extra.nvim#20]
**Describe the bug**
When I activate the code action to hide a false positive, the following error comes up:

```
[ltex_extra] [ERROR 12:41:26] ...tart/ltex-extra.nvim/lua/ltex_extra/src/commands-lsp.lua:69:Error catching ltex client
```
The files are written in the path specified in the config:
![image](https://user-images.githubusercontent.com/39244876/201530532-f1309385-b2db-4770-b69a-af59c94e73b6.png)

But they are ignored inside the editor (the warning about the ignored error keeps appearing.

**Expected behavior**
The ignored diagnostics should not show warnings.

**System:**
 - OS: macOS, Monterey, 12.6
 - Neovim version: 0.8
 - LTeX server installation method: mason

**Additional context**
My lsp and plugging config:

```lua
	if server == "ltex" then
		opt.settings = {
			ltex = {
				enabled = { "latex", "tex", "bib", "markdown" },
				language = "en-US",
				diagnosticSeverity = "information",
				setenceCacheSize = 2000,
				checkFrequency = "edit",
				trace = { server = "verbose" },
				additionalRules = {
					enablePickyRules = true,
					motherTongue = "pt-BR",
				},
			},
		}

		opt.on_attach = function(client, bufnr)
			on_attach(client, bufnr)
			require("ltex_extra").setup({
				load_langs = { "en-US" }, -- table <string> : languages for witch dictionaries will be loaded
				init_check = true, -- boolean : whether to load dictionaries on startup
				path = home .. "/.config/nvim/grammar", -- string : path to store dictionaries. Relative path uses current working directory
				log_level = "debug", -- string : "none", "trace", "debug", "info", "warn", "error", "fatal"
			})
		end
	end

```
Here is a little video with the complete behavior:

https://user-images.githubusercontent.com/39244876/201530888-077e76ad-211c-408f-80dc-89ba59751532.mov

**Comment by barreiroleo** [comment]
Hello @felipejoribeiro, sorry for the lateness, I miss the notification.

I think you're using Lspsaga, there are a few similar reports. Please, see the docs: https://github.com/barreiroleo/ltex_extra.nvim#lspsaga, and similar reports like #17.
I can't work on this for now because I don't use that plugin and don't have time to inspect the code of Lspsaga. PRs are welcome.
