### ISSUE TITLE
Error catching ltex client

### ISSUE THREAD

**Issue by dbucher97** [barreiroleo/ltex_extra.nvim#23]
**The Bug**
When performing a code action command, like add to a dictionary, the word is added to the dictionary file, but the config of `ltex` is not updated, with the error that the `ltex` client could not be catched. The result is that the word is still unknown to `ltex`. However, when restarting nvim, the correct dictionary is loaded and the word is known.

The reason for this bug is that `vim.lsp.buf_get_clients()` does return an empty dict for a reason I belive I can explain later.

Log:
```
Error catching ltex client
[ltex_extra] [TRACE 12:49:10] ...tart/ltex_extra.nvim/lua/ltex_extra/src/commands-lsp.lua:90: addToDictionary
[ltex_extra] [DEBUG 12:49:10] ...tart/ltex_extra.nvim/lua/ltex_extra/src/commands-lsp.lua:93: Lang: '"en-US"' Words: '{ "rrest
" }'
[ltex_extra] [TRACE 12:49:10] ...acker/start/ltex_extra.nvim/lua/ltex_extra/src/utils.lua:61: Exporting  dictionary en-US { "r
rest" }
[ltex_extra] [TRACE 12:49:10] ...acker/start/ltex_extra.nvim/lua/ltex_extra/src/utils.lua:37: Checking dir .ltex/
[ltex_extra] [TRACE 12:49:10] ...acker/start/ltex_extra.nvim/lua/ltex_extra/src/utils.lua:13: Checking path  .ltex/
[ltex_extra] [TRACE 12:49:10] ...acker/start/ltex_extra.nvim/lua/ltex_extra/src/utils.lua:50: Writing  .ltex/ltex.dictionary.e
n-US.txt
[ltex_extra] [TRACE 12:49:10] ...tart/ltex_extra.nvim/lua/ltex_extra/src/commands-lsp.lua:57: updateConfig
[ltex_extra] [TRACE 12:49:10] ...tart/ltex_extra.nvim/lua/ltex_extra/src/commands-lsp.lua:13: catch_ltex
[ltex_extra] [ERROR 12:49:10] ...tart/ltex_extra.nvim/lua/ltex_extra/src/commands-lsp.lua:71: Error catching ltex client
```

**To Reproduce**
1. `ltex-ls` installed through `mason.nvim`
2. Setup for `ltex`:
```lua
require("lspconfig").ltex.setup {
    on_attach = function(_, _)
        -- your other on_attach functions.
        require("ltex_extra").setup {
            load_langs = { "en-US", "de-DE" },
            init_check = true,
            path = ".ltex",
            log_level = "trace",
        }
    end,
    settings = {
        ltex = {
            additionalRules = {
                languageModel = "~/.ngrams/",
                motherTounge = "de-DE",
            },
        },
    },
}
```
3. Open a simple markdown file and insert a non-known word.
4. Add a word to the dictionary through code actions.

**Expected behavior**
Add the word to the dictionary and update the `ltex` configuration

**Possible Reason**
Neovim often has weird behavior when interacting with the API through callbacks. That's why the API features methods like `schedule` that execute a function inside the main event loop. Wrapping the `updateConfig` function with `vim.schedule` will probably fix this issue.

I will shortly open a PR with a version that works for me.

**System:**
 - OS: macOS
 - Neovim version: 0.8.2
 - LTeX server intallation method: mason

**Comment by barreiroleo** [comment]
Hello @dbucher97, I will check the PR, the argument makes sense. Thank you
