### ISSUE TITLE
Error catching ltex client

### ISSUE THREAD

**Issue by r3k2** [barreiroleo/ltex_extra.nvim#28]
Hello, I am trying to get language tool to work, I am using lazy and Mason...
I keep getting:
![swappy-20230309-085359](https://user-images.githubusercontent.com/5316229/223957145-2a99eba5-aed5-47c0-adbb-678128733ba5.png)
also cant't find how to get "spell suggestions" or substitute with correct suggestions for grammar like I can do in the browser.
my config is:
```
return {
    require("lspconfig").ltex.setup {
        capabilities = capabilities,
        -- on_attach = function(client, bufnr)
        on_attach = on_attach,
        -- your other on_attach functions.
        require("ltex_extra").setup {
            load_langs = { "es", "en-US" }, -- table <string> : languages for witch dictionaries will be loaded
            init_check = true,              -- boolean : whether to load dictionaries on startup
            path = nil,                     -- string : path to store dictionaries. Relative path uses current working directory
            log_level = "none",             -- string : "none", "trace", "debug", "info", "warn", "error", "fatal"
        },
        settings = {
            ltex = {
                language = "auto",
                additionalRules = {
                    enablePickyRules = true,
                    motherTongue = "es",
                },
            }
        }
    }
}
```
the return {} is because of auto load for lazy.nvim
how can I enable this for all files, txt,markdown,html etc?

**Comment by gwarf** [comment]
For the record I'm also trying to use ltex_extra with LazyVim, and I'm failing. I opened a discussion in the LazyVim repo: https://github.com/LazyVim/LazyVim/discussions/403

**Comment by fhfuih** [comment]
Currently, `require("ltex_extra").setup` needs to be called *inside `on_attach`*. So your config should look like
```lua
return {
    require("lspconfig").ltex.setup {
        capabilities = capabilities,
        -- on_attach = function(client, bufnr)
        on_attach = function(...)
            your_on_attach_function(...)
            require("ltex_extra").setup {
                load_langs = { "es", "en-US" }, -- table <string> : languages for witch dictionaries will be loaded
                init_check = true,              -- boolean : whether to load dictionaries on startup
                path = nil,                     -- string : path to store dictionaries. Relative path uses current working directory
                log_level = "none",             -- string : "none", "trace", "debug", "info", "warn", "error", "fatal"
            }
        end,
        settings = {
            ltex = {
                language = "auto",
                additionalRules = {
                    enablePickyRules = true,
                    motherTongue = "es",
                },
            }
        }
    }
}
```

I also just posted a PR #29 to change the setup method of this package to something more like typescript, rust, and flutter extensions.

**Comment by r3k2** [comment]
Hello, Thank you! This seems clear (kind of) I have no idea about LUA I come from C/GO/Rust, but I can look things up, no problem, the issue is that I asked a similar question here: https://github.com/LazyVim/LazyVim/discussions/403#discussioncomment-5319825 and the reply from lazy Vim is super complicated and does not look at all like my modular config, seems they have all in one file, and it confuses me been a Lua noob.
I made your changes and still does not seem to work, my original config has as base this: https://github.com/nvim-lua/kickstart.nvim I included a folder with my own custom configs so I do not touch the main lua.ini like ~/.config/nvim/lua/plugins and in there I have some .lua files like this one that is called ltex.lua

**Comment by gwarf** [comment]
The discussions I started is about using this with [LazyVim](https://github.com/LazyVim/LazyVim), a neovim setup based on [lazy.nvim](https://github.com/folke/lazy.nvim), the naming can be confusing, they are two different but related things.
That's probably why what I end to use it's quite different from your setup, as it's relying on the [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) set up put in place by LazyVim: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/init.lua.

In the example @fhfuih provided, it's customising the `on_attach` for ltex, calling first the general on_attach "`your_on_attach_function`", that maybe something like what is documented here: https://github.com/neovim/nvim-lspconfig#suggested-configuration (and AFAICS from your code example you have such a function alredy called `on_attach`), then  doing the calling the set up fucnction of ltex_extra.

**Comment by fhfuih** [comment]
Hey @gwarf we actually posted at the same time! XD

And also, you can check my fork of `ltex_extra`, which changes the way to set up this plugin (similar to flutter, typescript, rust tools). I have also made a PR. Seems the project owner is quite busy recently.

**Comment by gwarf** [comment]
Yes, saw this when posting, cheers :D

**Comment by r3k2** [comment]
@gwarf oh wait! so, this is something different from the plugin loader lazy.vim? OMG sorry I had no idea, I have been trying to get LaTeX_extra etc to work for the grammar checker for weeks with no luck using the installation setup I posted above and then extending based on that now this one here, sorry. Going o read what you both reply to me in detail when I get home see if I can get something out of it. 
thanks

**Comment by fhfuih** [comment]
> @gwarf oh wait! so, this is something different from the plugin loader lazy.vim? OMG sorry I had no idea, I have been trying to get LaTeX_extra etc to work for the grammar checker for weeks with no luck using the installation setup I posted above and then extending based on that now this one here, sorry. Going o read what you both reply to me in detail when I get home see if I can get something out of it. thanks

Actually I think the difference is not that significant. Because the `lazy.nvim` package manager itself has introduced a [recommended config file structure](https://github.com/folke/lazy.nvim#-structuring-your-plugins), and the distro LazyVim just follows this paradigm. Also, the distro LazyVim does not introduce another abstraction layer for user configuration on top of it, but it invites users to fork the distro configuration and change it directly. So it is pretty much another [kickstart](https://github.com/nvim-lua/kickstart.nvim) configuration template. Have fun tweaking neovim XD

**Comment by barreiroleo** [comment]
I've launched a new release. I've merged the @fhfuih proposal with a few changes to make the two ways of config compatible. A `lazy.nvim` config is provided in the docs.
