### ISSUE TITLE
No trailing separator for `path` option

### ISSUE THREAD

**Issue by vandalt** [barreiroleo/ltex_extra.nvim#32]
**Describe the bug**
When setting the `path` option, trailing separators are not added by default, and they are removed if one is added manually. I get a warning saying that the path `/home/vandal/.local/share/ltexltex.hiddenFalsePositives.en-US.txt` does not exist. I think this behaviour is introduced by `vim.fs.normalize()`, added in #26. For example:

- `:lua print(vim.fn.expand("~") .. "/.local/share/ltex/")` gives the trailing slash
- `:lua print(vim.fs.normalize(vim.fn.expand("~") .. "/.local/share/ltex/"))` does not show a trailing slash

I think moving `.. "/"` outside of `vim.fs.normalize()` [here](https://github.com/barreiroleo/ltex_extra.nvim/blob/1d2f288ceedc70d5a9c00f55c0d0cc788b5164f2/lua/ltex_extra/init.lua#L15) would fix the issue. I tried locally and it seemed to work. Let me know if I should send a PR or if you prefer to do it directly.

Here is my config for `ltex_extra`:

```lua
  require("ltex_extra").setup{
    load_langs = { "fr", "en-US" },
    init_check = true, -- boolean : whether to load dictionaries on startup
    path = vim.fn.expand("~") .. "/.local/share/ltex/",
    log_level = "warn"
  }
```

**To Reproduce**
1. Use the config shown above
2. Load a file that uses ltex
3. Get the warning described above

**Expected behavior**
The trailing separator should be kept when added manually, and probably added automatically when not present.

**System:**
 - OS: Linux
 - Neovim version: 0.9.0
 - LTeX server intallation method: mason

**Comment by barreiroleo** [comment]
I'm working on a couple of changes to the setup way, that line will be changed soon. So, many thanks for the test case

**Comment by barreiroleo** [comment]
The new release should fix this. Please, open a new issue if you continue with troubles. Thanks

**Comment by vandalt** [comment]
Indeed, it's fixed now. Thanks a lot!
