### ISSUE TITLE
Problem with creating a directory when absolute path is specified

### ISSUE THREAD

**Issue by Iljo** [barreiroleo/ltex_extra.nvim#41]
There is a problem if `path` is set as absolute path, and last directory in the path is missing, i.e. should be created. So, an error is displayed when trying to add some word to a dictionary in that case. This is what is displayed:

```lua
Failed making directory:
```
```lua
Error executing vim.schedule lua callback: ...efined/start/ltex_extra.nvim/lua/ltex_extra/utils/fs.lua:56: attempt to index local 'stat' (a nil value)
stack traceback:
        ...efined/start/ltex_extra.nvim/lua/ltex_extra/utils/fs.lua:56: in function 'check_dir'
        ...efined/start/ltex_extra.nvim/lua/ltex_extra/utils/fs.lua:79: in function 'exportFile'
        ...ed/start/ltex_extra.nvim/lua/ltex_extra/commands-lsp.lua:96: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:651: in function 'apply_action'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:697: in function 'on_choice'
        /usr/share/nvim/runtime/lua/vim/ui.lua:54: in function 'select'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:708: in function 'on_code_action_results'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:726: in function 'callback'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:2021: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**To Reproduce**
1. Configure ltex_extra to have `path` variable set as absolute path to directory. Something like 
    `/home/user/Documents/Test Path`.
2. Make sure that the last directory is missing. (`Test Path` in the example)
3. Misspell some word, or make up a new word.
2. Try to add that word to a dictionary through code action.
4. See error above.

**Expected behavior**
A word should be added to a dictionary. And as it's the case when the relative path is provided and last directory is missing, it should be created.

**System:**
 - OS: Linux
 - Neovim version: stable
 - LTeX server intallation method: manual
 - ltex_extra version: currently, the latest commit f32a4ca

**Edit:**
Originally, the issue was reporting the problem with spaces in path. But actually, the problem with spaces was when I was using the version at commit 3ceb240. Then I updated to the latest version, and taught it's still the same problem, just with a different error message. It's not, the different error message refers to the bug with an absolute path, that's why I've updated the bug report, and didn't create a new issue.

**Comment by barreiroleo** [comment]
PR merged, very thanks!
