### ISSUE TITLE
Provide a default language

### ISSUE THREAD

**Issue by barreiroleo** [barreiroleo/ltex_extra.nvim#45]
Actually is an issue. Probably when I wrote this, `en-US` was working as default for the code action.
Thanks!

_Note to self: Add default lang for `updateConfigFull` or insert one at setup if the table is empty._

_Originally posted by @barreiroleo in https://github.com/barreiroleo/ltex_extra.nvim/issues/43#issuecomment-1656560865_

**Comment by DannyStoll1** [comment]
I think it is ok not to have a default language for now, as long as the docs clarify that the language needs to be manually specified (see #49)
