### ISSUE TITLE
Replacement suggestions via quick fixes

### ISSUE THREAD

**Issue by timoleistner** [barreiroleo/ltex_extra.nvim#8]
**Is your feature request related to a problem? Please describe.**
It's cumbersome to look for the correct spelling on Google and type it in.

**Describe the solution you'd like**
A code action to accept a ltex suggestion, possibly mappable.

**Describe alternatives you've considered**
VSC is not an option.

**Additional context**
As you've implemented the other extra features the VSC plugin for ltex provides, the "accept quick fix suggestion" option is missing.
I've also noticed, that I don't even have suggestions - is there a way to turn this on or do I need an extra dictionary for that?

The feature is described [here](https://valentjn.github.io/ltex/faq.html#how-can-i-map-the-use--quick-fix-to-a-keyboard-shortcut-in-vs-code) and [here](https://github.com/valentjn/vscode-ltex/issues/297) and the [ltex main website](https://valentjn.github.io/ltex/index.html) also suggests that this feature exists natively (Replacement suggestions via quick fixes).

Edit: found another [source](https://valentjn.github.io/ltex/ltex-ls/server-usage.html#quick-fixes).

**Comment by barreiroleo** [comment]
Hi @timoleistner
In theory, from docs, it's possible to do that with a map to something like `:lua vim.lsp.buf.code_action { contex = { only = { "quickfix.ltex.acceptSuggestions" } }, apply = true }`
Unfortunately, doing a quick test, it doesn't work as expected. If I get it to work I might offer an api to map. I don't know if it makes sense.

LTeX don't offer suggestion as you type. You can use an autocompletion source from buffer. In my case, I use nvim-cmp + cmp-buffer, both from hrsh7th.

**Comment by timoleistner** [comment]
Using [cmp-dictionary](https://github.com/uga-rosa/cmp-dictionary) might offer correction suggestions if one uses a heuristic search like fzf or simple Levenshtein distance to compare the word marked by ltex with the dictionary and rank the best possible suggestions :thinking: but this might be out of the scope of this plugin.

**Comment by barreiroleo** [comment]
> It's cumbersome to look for the correct spelling on Google and type it in.

Rereading your first message, I doubt if you are using the vim's LSP commands: `vim.diagnostic.goto_next()` + `vim.lsp.buf.code_action()`.

LTeX_extra already notifies LTeX of the words in the dictionary when an `add to dictionary` code_action has been performed.

So, LTeX takes its time to make the diagnosis. Real-time suggestion powered by LTeX is something I can't see clearly. On the other hand, real-time rough suggestions based on the content of the ltex dictionary might be possible by creating a source of completion.
Probably the final combinations could be "cmp-buffer" + "cmp-dictionary" + "cmp-ltex" or something like that.

**Comment by timoleistner** [comment]
You're right... there are suggestions by code action, I don't know what I was thinking. Can be closed, sorry for the hassle.

**Comment by barreiroleo** [comment]
Don't worry, you gave me a good idea for expose quick commands. Apparently there's an issue with the filters on the kinds of quickfixes on the server side. I don't have much time, but I'm on it.
